# Generated by Django 4.1 on 2022-09-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
