# Generated by Django 4.1 on 2022-08-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photolist', '0002_post_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='place',
            field=models.CharField(max_length=20),
        ),
    ]
