# Generated by Django 4.1 on 2022-08-19 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photolist', '0003_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='message',
        ),
    ]
